# Form implementation generated from reading ui file 'Poker_inter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt6.QtGui import QPixmap
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QLabel, QMainWindow
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import *

from classes import *
from output_functoins import *

SCREEN_SIZE = [400, 400]


class Ui_MainWindow(QMainWindow):
    def update_inf(self):
        self.update_bets()
        self.whose_turn()

    def text_console(self, turn, text):
        self.Player_1_console.setText('')
        self.Player_2_console.setText('')
        self.Player_3_console.setText('')
        self.Player_4_console.setText('')
        if turn == 0:
            self.Player_1_console.setText(text)
        elif turn == 1:
            self.Player_2_console.setText(text)
        elif turn == 2:
            self.Player_3_console.setText(text)
        elif turn == 3:
            self.Player_4_console.setText(text)

    def push_last_bet_main(self): return last_bet

    def update_bets(self):
        players = get_players()
        self.Player_1_bet_numb.setText(str(players[0].n_bet))
        self.Player_2_bet_numb.setText(str(players[1].n_bet))
        self.Player_3_bet_numb.setText(str(players[2].n_bet))
        self.Player_4_bet_numb.setText(str(players[3].n_bet))
        self.Player_1_bank_numb.setText(str(players[0].player_money))
        self.Player_2_bank_numb.setText(str(players[1].player_money))
        self.Player_3_bank_numb.setText(str(players[2].player_money))
        self.Player_4_bank_numb.setText(str(players[3].player_money))

    def whose_turn(self):
        turn = get_turn()
        players = get_players()
        self.text_console(turn, 'Your turn')

    def player_answer(self, ans, number, bet = '0'):
        #print(2)
        turn = get_turn()
        players = get_players()
        #self.text_console(turn, 'Please, enter a number')
        print(ans, number)
        if number == turn + 1:
            if ans == 'c':
                print(12)
                main_player_answer('c', bet)
                self.player_bets_counter += 1
            if ans == 'f':
                self.player_bets_counter += 1
                main_player_answer('f', bet)

            if ans == 'r':
                try:
                    bet = int(bet)
                    main_player_answer('r', bet)
                except ValueError:
                    self.text_console(turn, 'Please enter a number')
        self.update_inf()



    def raise_command(self, number):
        #print(1)
        #global last_bet
        turn = get_turn()
        players = get_players()
        #command = self.line_edit.text()
        l = ''
        if number == 1:
            l = self.Player_1_r_lineEdit.text()
        elif number == 2:
            l = self.Player_2_r_lineEdit.text()
        elif number == 3:
            l = self.Player_3_r_lineEdit.text()
        elif number == 4:
            l = self.Player_4_r_lineEdit.text()
        self.player_answer('r', number, str(l))


        #self.Player_1_fold_button.clear()
        # last_bet = get_last_bet()
        # m_bet = get_m_bet()
        # while True:
        #     try:
        #         command = int(command)
        #         if command < last_bet:
        #             self.text_console(turn, 'Enter a raise bet')
        #             continue
        #         break
        #     except ValueError:
        #         self.text_console(turn, 'Enter a numder')
        # for pla in players:
        #     if pla.player_money < command:
        #         command = pla.player_money
        # last_bet = command - (command % m_bet)
        # players[turn].n_bet = last_bet


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.Player_1_pos = ''
        self.Player_2_pos = ''
        self.Player_3_pos = ''
        self.Player_4_pos = ''
        self.player_bets_counter = 0

        MainWindow.resize(688, 683)
        new_width, new_height = 80, 120
        MainWindow.setStyleSheet("background-color: rgb(186, 231, 226);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Flop_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Flop_text.setGeometry(QtCore.QRect(0, 40, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Flop_text.setFont(font)
        self.Flop_text.setStyleSheet("background-color: rgb(255, 183, 176);")
        self.Flop_text.setObjectName("Flop_text")
        self.Turn_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Turn_text.setGeometry(QtCore.QRect(290, 40, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Turn_text.setFont(font)
        self.Turn_text.setStyleSheet("background-color: rgb(255, 183, 176);")
        self.Turn_text.setObjectName("Turn_text")
        self.River_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.River_text.setGeometry(QtCore.QRect(400, 40, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.River_text.setFont(font)
        self.River_text.setStyleSheet("background-color: rgb(255, 183, 176);")
        self.River_text.setObjectName("River_text")
        self.card_5_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_5_text.setGeometry(QtCore.QRect(390, 110, 101, 31))
        self.card_5_text.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_5_text.setIndent(-1)
        self.card_5_text.setObjectName("card_5_text")
        self.card_4_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_4_text.setGeometry(QtCore.QRect(290, 110, 101, 31))
        self.card_4_text.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_4_text.setIndent(-1)
        self.card_4_text.setObjectName("card_4_text")
        self.card_2_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_2_text.setGeometry(QtCore.QRect(100, 110, 101, 31))
        self.card_2_text.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_2_text.setIndent(-1)
        self.card_2_text.setObjectName("card_2_text")
        self.card_3_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_3_text.setGeometry(QtCore.QRect(200, 110, 91, 31))
        self.card_3_text.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_3_text.setIndent(-1)
        self.card_3_text.setObjectName("card_3_text")
        self.card_1_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_1_text.setGeometry(QtCore.QRect(0, 110, 101, 31))
        self.card_1_text.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_1_text.setIndent(-1)
        self.card_1_text.setObjectName("card_1_text")
        self.Bank_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Bank_text.setGeometry(QtCore.QRect(490, 0, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Bank_text.setFont(font)
        self.Bank_text.setStyleSheet("background-color: rgb(181, 255, 175);")
        self.Bank_text.setObjectName("Bank_text")
        self.Bank_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Bank_numb.setGeometry(QtCore.QRect(490, 80, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Bank_numb.setFont(font)
        self.Bank_numb.setStyleSheet("background-color: rgb(181, 255, 175);")
        self.Bank_numb.setObjectName("Bank_numb")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 0, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 0, 91, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        #self.pixmap = QPixmap('../data/images_b/card_2.jpg')
        #self.pixmap = QPixmap(show_cards_way(Card("Буби", 'A')))
        #self.pixmap.scaled(1, 1)
        # Если картинки нет, то QPixmap будет пустым,
        # Отображаем содержимое QPixmap в объекте QLabel
        #self.image.setPixmap(self.pixmap)

        self.card_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_6.setGeometry(QtCore.QRect(0, 150, new_width, new_height))
        #self.card_6.setPixmap(self.pixmap)

        self.card_6.setStyleSheet("background-color: rgb(181, 181, 181);""color: rgb(255, 255, 255);")
        self.card_6.setText("")
        self.card_6.setIndent(-1)

        self.card_6.setObjectName("card_6")
        self.card_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_7.setGeometry(QtCore.QRect(100, 150, new_width, new_height))
        self.card_7.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_7.setText("")
        self.card_7.setIndent(-1)
        self.card_7.setObjectName("card_7")
        self.card_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_8.setGeometry(QtCore.QRect(200, 150, new_width, new_height))
        self.card_8.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_8.setText("")
        self.card_8.setIndent(-1)
        self.card_8.setObjectName("card_8")
        self.card_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_9.setGeometry(QtCore.QRect(300, 150, new_width, new_height))
        self.card_9.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_9.setText("")
        self.card_9.setIndent(-1)
        self.card_9.setObjectName("card_9")
        self.card_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_10.setGeometry(QtCore.QRect(400, 150, new_width, new_height))
        self.card_10.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.card_10.setText("")
        self.card_10.setIndent(-1)
        self.card_10.setObjectName("card_10")
        self.Player_1_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_text.setGeometry(QtCore.QRect(0, 281, 91, 31))
        self.Player_1_text.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Player_1_text.setObjectName("Player_1_text")

        self.Player_1_card_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_card_1.setGeometry(QtCore.QRect(0, 331, new_width, new_height))
        self.Player_1_card_1.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[0].player_deck[0]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_1_card_1.setPixmap(self.pixmap)
        self.Player_1_card_1.setText("")
        self.Player_1_card_1.setIndent(-1)
        self.Player_1_card_1.setObjectName("Player_1_card_1")

        self.Player_1_card_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_card_2.setGeometry(QtCore.QRect(100, 331, new_width, new_height))
        self.Player_1_card_2.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[0].player_deck[1]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_1_card_2.setPixmap(self.pixmap)
        self.Player_1_card_2.setText("")
        self.Player_1_card_2.setIndent(-1)
        self.Player_1_card_2.setObjectName("Player_1_card_2")

        self.Player_1_check_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_1_check_button.setGeometry(QtCore.QRect(200, 331, 91, 23))
        self.Player_1_check_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_1_check_button.setObjectName("Player_1_check_button")\

        self.Player_1_check_button.clicked.connect(lambda: self.player_answer('c', 1))

        self.Player_1_fold_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_1_fold_button.setGeometry(QtCore.QRect(200, 361, 91, 23))
        self.Player_1_fold_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_1_fold_button.setObjectName("Player_1_fold_button")

        self.Player_1_fold_button.clicked.connect(lambda: self.player_answer('f', 1))

        # self.Player_1_raise_button = QtWidgets.QPushButton(parent=self.centralwidget)
        # self.Player_1_raise_button.setGeometry(QtCore.QRect(200, 391, 91, 23))
        # self.Player_1_raise_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Player_1_raise_button.setObjectName("Player_1_raise_button")
        #
        # self.Player_1_raise_button.clicked.connect(lambda: self.player_answer('r', 1))

        self.Player_1_r_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Player_1_r_lineEdit.setGeometry(QtCore.QRect(200, 420, 91, 31))
        self.Player_1_r_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_1_r_lineEdit.setObjectName("Player_1_r_lineEdit")

        self.Player_1_r_lineEdit.returnPressed.connect(lambda: self.raise_command(1))

        self.Player_1_bet_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_bet_text.setGeometry(QtCore.QRect(100, 281, 61, 16))
        self.Player_1_bet_text.setObjectName("Player_1_bet_text")
        self.Player_1_bank_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_bank_text.setGeometry(QtCore.QRect(100, 301, 71, 16))
        self.Player_1_bank_text.setObjectName("Players_1_bank_text")
        self.Player_1_bet_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_bet_numb.setGeometry(QtCore.QRect(170, 281, 51, 16))
        self.Player_1_bet_numb.setObjectName("Player_1_bet_numb")
        self.Player_1_bank_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_bank_numb.setGeometry(QtCore.QRect(170, 301, 51, 16))
        self.Player_1_bank_numb.setObjectName("Players_1_bank_numb")
        self.Player_2_bank_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_bank_numb.setGeometry(QtCore.QRect(470, 300, 51, 16))
        self.Player_2_bank_numb.setObjectName("Players_2_bank_numb")
        self.Player_2_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_text.setGeometry(QtCore.QRect(300, 280, 91, 31))
        self.Player_2_text.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Player_2_text.setObjectName("Player_2_text")
        self.Player_2_bank_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_bank_text.setGeometry(QtCore.QRect(400, 300, 71, 16))
        self.Player_2_bank_text.setObjectName("Players_2_bank_text")

        self.Player_2_card_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_card_1.setGeometry(QtCore.QRect(300, 330, new_width, new_height))
        self.Player_2_card_1.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[1].player_deck[0]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_2_card_1.setPixmap(self.pixmap)
        self.Player_2_card_1.setText("")
        self.Player_2_card_1.setIndent(-1)
        self.Player_2_card_1.setObjectName("Player_2_card_1")

        self.Player_2_card_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_card_2.setGeometry(QtCore.QRect(400, 330, new_width, new_height))
        self.Player_2_card_2.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[1].player_deck[1]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_2_card_2.setPixmap(self.pixmap)
        self.Player_2_card_2.setText("")
        self.Player_2_card_2.setIndent(-1)
        self.Player_2_card_2.setObjectName("Player_2_card_2")

        self.Player_2_bet_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_bet_numb.setGeometry(QtCore.QRect(470, 280, 51, 16))
        self.Player_2_bet_numb.setObjectName("Player_2_bet_numb")
        self.Player_2_bet_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_bet_text.setGeometry(QtCore.QRect(400, 280, 61, 16))
        self.Player_2_bet_text.setObjectName("Player_2_bet_text")
        self.Player_3_bank_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_bank_numb.setGeometry(QtCore.QRect(170, 480, 51, 16))
        self.Player_3_bank_numb.setObjectName("Players_3_bank_numb")
        self.Player_3_bank_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_bank_text.setGeometry(QtCore.QRect(100, 480, 71, 16))
        self.Player_3_bank_text.setObjectName("Players_3_bank_text")
        self.Player_3_card_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_card_1.setGeometry(QtCore.QRect(0, 510, new_width, new_height))
        self.Player_3_card_1.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[2].player_deck[0]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_3_card_1.setPixmap(self.pixmap)
        self.Player_3_card_1.setText("")
        self.Player_3_card_1.setIndent(-1)
        self.Player_3_card_1.setObjectName("Player_3_card_1")

        self.Player_3_card_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_card_2.setGeometry(QtCore.QRect(100, 510, new_width, new_height))
        self.Player_3_card_2.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[2].player_deck[1]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_3_card_2.setPixmap(self.pixmap)
        self.Player_3_card_2.setText("")
        self.Player_3_card_2.setIndent(-1)
        self.Player_3_card_2.setObjectName("Player_3_card_2")

        self.Player_3_bet_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_bet_numb.setGeometry(QtCore.QRect(170, 460, 51, 16))
        self.Player_3_bet_numb.setObjectName("Player_3_bet_numb")
        self.Player_3_bet_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_bet_text.setGeometry(QtCore.QRect(100, 460, 61, 16))
        self.Player_3_bet_text.setObjectName("Player_3_bet_text")
        self.Player_4_bank_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_bank_numb.setGeometry(QtCore.QRect(470, 480, 51, 16))
        self.Player_4_bank_numb.setObjectName("Players_4_bank_numb")
        self.Player_4_bank_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_bank_text.setGeometry(QtCore.QRect(400, 480, 71, 16))
        self.Player_4_bank_text.setObjectName("Players_4_bank_text")
        self.Player_4_card_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_card_1.setGeometry(QtCore.QRect(300, 510, new_width, new_height))
        self.Player_4_card_1.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[3].player_deck[0]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_4_card_1.setPixmap(self.pixmap)
        self.Player_4_card_1.setText("")
        self.Player_4_card_1.setIndent(-1)
        self.Player_4_card_1.setObjectName("Player_4_card_1")

        self.Player_4_card_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_card_2.setGeometry(QtCore.QRect(400, 510, new_width, new_height))
        self.Player_4_card_2.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"color: rgb(255, 255, 255);")
        self.pixmap = QPixmap(show_cards_way(get_players()[3].player_deck[1]))
        self.pixmap = self.pixmap.scaled(new_width, new_height)
        self.Player_4_card_2.setPixmap(self.pixmap)
        self.Player_4_card_2.setText("")
        self.Player_4_card_2.setIndent(-1)
        self.Player_4_card_2.setObjectName("Player_4_card_2")
        self.Player_4_bet_numb = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_bet_numb.setGeometry(QtCore.QRect(470, 460, 51, 16))
        self.Player_4_bet_numb.setObjectName("Player_4_bet_numb")
        self.Player_4_bet_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_bet_text.setGeometry(QtCore.QRect(400, 460, 61, 16))
        self.Player_4_bet_text.setObjectName("Player_4_bet_text")

        # self.Player_2_raise_button = QtWidgets.QPushButton(parent=self.centralwidget)
        # self.Player_2_raise_button.setGeometry(QtCore.QRect(500, 390, 91, 23))
        # self.Player_2_raise_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Player_2_raise_button.setObjectName("Player_2_raise_button")
        #
        # self.Player_2_raise_button.clicked.connect(lambda: self.player_answer('r', 2))

        self.Player_2_r_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Player_2_r_lineEdit.setGeometry(QtCore.QRect(500, 419, 91, 31))
        self.Player_2_r_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_2_r_lineEdit.setObjectName("Player_2_r_lineEdit")

        self.Player_2_r_lineEdit.returnPressed.connect(lambda: self.raise_command(2))

        self.Player_2_check_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_2_check_button.setGeometry(QtCore.QRect(500, 330, 91, 23))
        self.Player_2_check_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_2_check_button.setObjectName("Player_2_check_button")

        self.Player_2_check_button.clicked.connect(lambda: self.player_answer('c', 2))

        self.Player_2_fold_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_2_fold_button.setGeometry(QtCore.QRect(500, 360, 91, 23))
        self.Player_2_fold_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_2_fold_button.setObjectName("Player_2_fold_button")

        self.Player_2_fold_button.clicked.connect(lambda: self.player_answer('f', 2))

        # self.Player_3_raise_button = QtWidgets.QPushButton(parent=self.centralwidget)
        # self.Player_3_raise_button.setGeometry(QtCore.QRect(200, 570, 91, 23))
        # self.Player_3_raise_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Player_3_raise_button.setObjectName("Player_3_raise_button")
        #
        # self.Player_3_raise_button.clicked.connect(lambda: self.player_answer('r', 3))

        self.Player_3_r_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Player_3_r_lineEdit.setGeometry(QtCore.QRect(200, 599, 91, 31))
        self.Player_3_r_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_3_r_lineEdit.setObjectName("Player_3_r_lineEdit")

        self.Player_3_r_lineEdit.returnPressed.connect(lambda: self.raise_command(3))

        self.Player_3_check_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_3_check_button.setGeometry(QtCore.QRect(200, 510, 91, 23))
        self.Player_3_check_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_3_check_button.setObjectName("Player_3_check_button")

        self.Player_3_check_button.clicked.connect(lambda: self.player_answer('c', 3))

        self.Player_3_fold_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_3_fold_button.setGeometry(QtCore.QRect(200, 540, 91, 23))
        self.Player_3_fold_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_3_fold_button.setObjectName("Player_3_fold_button")

        self.Player_3_fold_button.clicked.connect(lambda: self.player_answer('f', 3))

        # self.Player_4_raise_button = QtWidgets.QPushButton(parent=self.centralwidget)
        # self.Player_4_raise_button.setGeometry(QtCore.QRect(500, 570, 91, 23))
        # self.Player_4_raise_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Player_4_raise_button.setObjectName("Player_4_raise_button")
        #
        # self.Player_4_raise_button.clicked.connect(lambda: self.player_answer('r', 4))

        self.Player_4_r_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Player_4_r_lineEdit.setGeometry(QtCore.QRect(500, 599, 91, 31))
        self.Player_4_r_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_4_r_lineEdit.setObjectName("Player_4_r_lineEdit")

        self.Player_4_r_lineEdit.returnPressed.connect(lambda: self.raise_command(4))

        self.Player_4_check_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_4_check_button.setGeometry(QtCore.QRect(500, 510, 91, 23))
        self.Player_4_check_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_4_check_button.setObjectName("Player_4_check_button")

        self.Player_4_check_button.clicked.connect(lambda: self.player_answer('c', 4))

        self.Player_4_fold_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Player_4_fold_button.setGeometry(QtCore.QRect(500, 540, 91, 23))
        self.Player_4_fold_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_4_fold_button.setObjectName("Player_4_fold_button")

        self.Player_4_fold_button.clicked.connect(lambda: self.player_answer('f', 4))

        self.Player_3_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_text.setGeometry(QtCore.QRect(0, 460, 91, 31))
        self.Player_3_text.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Player_3_text.setObjectName("Player_3_text")
        self.Player_4_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_text.setGeometry(QtCore.QRect(300, 460, 91, 31))
        self.Player_4_text.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Player_4_text.setObjectName("Player_4_text")
        self.card_5_text_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_5_text_2.setGeometry(QtCore.QRect(500, 150, 61, 31))
        self.card_5_text_2.setStyleSheet("")
        self.card_5_text_2.setIndent(-1)
        self.card_5_text_2.setObjectName("card_5_text_2")
        self.card_5_text_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_5_text_3.setGeometry(QtCore.QRect(500, 180, 81, 31))
        self.card_5_text_3.setStyleSheet("")
        self.card_5_text_3.setIndent(-1)
        self.card_5_text_3.setObjectName("card_5_text_3")
        self.Player_1_console = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_1_console.setGeometry(QtCore.QRect(220, 300, 71, 20))
        self.Player_1_console.setStyleSheet("color: rgb(255, 0, 0);")
        self.Player_1_console.setObjectName("Player_1_console")
        self.Player_2_console = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_2_console.setGeometry(QtCore.QRect(520, 300, 71, 20))
        self.Player_2_console.setStyleSheet("color: rgb(255, 0, 0);")
        self.Player_2_console.setObjectName("Player_2_console")
        self.Player_3_console = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_3_console.setGeometry(QtCore.QRect(220, 480, 71, 20))
        self.Player_3_console.setStyleSheet("color: rgb(255, 0, 0);")
        self.Player_3_console.setObjectName("Player_3_console")
        self.Player_4_console = QtWidgets.QLabel(parent=self.centralwidget)
        self.Player_4_console.setGeometry(QtCore.QRect(520, 480, 71, 20))
        self.Player_4_console.setStyleSheet("color: rgb(255, 0, 0);")
        self.Player_4_console.setObjectName("Player_4_console")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Poker"))
        self.Flop_text.setText(_translate("MainWindow", "Flop"))
        self.Turn_text.setText(_translate("MainWindow", "Turn"))
        self.River_text.setText(_translate("MainWindow", "River"))
        self.card_5_text.setText(_translate("MainWindow", "Card 5"))
        self.card_4_text.setText(_translate("MainWindow", "Card 4"))
        self.card_2_text.setText(_translate("MainWindow", "Card 2"))
        self.card_3_text.setText(_translate("MainWindow", "Card 3"))
        self.card_1_text.setText(_translate("MainWindow", "Card 1"))
        self.Bank_text.setText(_translate("MainWindow", "Bank"))
        self.Bank_numb.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Settings"))
        self.pushButton_2.setText(_translate("MainWindow", "Game rules"))
        self.pushButton_3.setText(_translate("MainWindow", "Restart game"))
        self.Player_1_text.setText(_translate("MainWindow", "Player 1"))
        self.Player_1_check_button.setText(_translate("MainWindow", "Check"))
        self.Player_1_fold_button.setText(_translate("MainWindow", "Fold"))
        #self.Player_1_raise_button.setText(_translate("MainWindow", "Raise"))
        self.Player_1_bet_text.setText(_translate("MainWindow", "Players bet:"))
        self.Player_1_bank_text.setText(_translate("MainWindow", "Players bank:"))
        self.Player_1_bet_numb.setText(_translate("MainWindow", "0"))
        self.Player_1_bank_numb.setText(_translate("MainWindow", "1000"))
        self.Player_2_bank_numb.setText(_translate("MainWindow", "1000"))
        self.Player_2_text.setText(_translate("MainWindow", "Player 2"))
        self.Player_2_bank_text.setText(_translate("MainWindow", "Players bank:"))
        self.Player_2_bet_numb.setText(_translate("MainWindow", "0"))
        self.Player_2_bet_text.setText(_translate("MainWindow", "Players bet:"))
        self.Player_3_bank_numb.setText(_translate("MainWindow", "1000"))
        self.Player_3_bank_text.setText(_translate("MainWindow", "Players bank:"))
        self.Player_3_bet_numb.setText(_translate("MainWindow", "0"))
        self.Player_3_bet_text.setText(_translate("MainWindow", "Players bet:"))
        self.Player_4_bank_numb.setText(_translate("MainWindow", "1000"))
        self.Player_4_bank_text.setText(_translate("MainWindow", "Players bank:"))
        self.Player_4_bet_numb.setText(_translate("MainWindow", "0"))
        self.Player_4_bet_text.setText(_translate("MainWindow", "Players bet:"))
        #self.Player_2_raise_button.setText(_translate("MainWindow", "Raise"))
        self.Player_2_check_button.setText(_translate("MainWindow", "Check"))
        self.Player_2_fold_button.setText(_translate("MainWindow", "Fold"))
        #self.Player_3_raise_button.setText(_translate("MainWindow", "Raise"))
        self.Player_3_check_button.setText(_translate("MainWindow", "Check"))
        self.Player_3_fold_button.setText(_translate("MainWindow", "Fold"))
        #self.Player_4_raise_button.setText(_translate("MainWindow", "Raise"))
        self.Player_4_check_button.setText(_translate("MainWindow", "Check"))
        self.Player_4_fold_button.setText(_translate("MainWindow", "Fold"))
        self.Player_3_text.setText(_translate("MainWindow", "Player 3"))
        self.Player_4_text.setText(_translate("MainWindow", "Player 4"))
        self.card_5_text_2.setText(_translate("MainWindow", "Minimal bet:"))
        self.card_5_text_3.setText(_translate("MainWindow", "Minimal bet step:"))
        self.Player_1_console.setText(_translate("MainWindow", "Er"))
        self.Player_2_console.setText(_translate("MainWindow", "Er"))
        self.Player_3_console.setText(_translate("MainWindow", "Er"))
        self.Player_4_console.setText(_translate("MainWindow", "Er"))








if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()
    start_game()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    ui.update_inf()



    MainWindow.show()

    #main_game()
    sys.exit(app.exec())

